//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 IBOM.rc 使用
//
#define IDCANCEL2                       3
#define ID_BTN_DEFAULT                  3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_FILE_CTRL_VIEW              101
#define IDS_OUTPUT_INFO_VIEW            102
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IBOMTYPE                    130
#define IDD_INPUT_DLG                   130
#define ID_WINDOW_MANAGER               131
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDD_INPUT_AN_INTEGER_VAL_DLG    186
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        202
#define ID_VIEW_APPLOOK_OFF_XP          203
#define ID_VIEW_APPLOOK_WIN_XP          204
#define ID_VIEW_APPLOOK_OFF_2003        205
#define ID_VIEW_APPLOOK_VS_2005         206
#define ID_VIEW_APPLOOK_VS_2008         207
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   208
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  209
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 210
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   211
#define ID_VIEW_APPLOOK_WINDOWS_7       212
#define ID_SNAP                         214
#define ID_MOVE                         215
#define ID_ZOOM                         216
#define ID_IMPORT_DWG_BOM               217
#define ID_EXPORT_DWG_BOM               218
#define ID_IMPORT_IMAGE_FOLDER          219
#define ID_IMPORT_IMAGE_FILE            220
#define ID_IMPORT_LOFT_BOM              221
#define ID_DELETE_ITEM                  222
#define ID_ADD_SEG_DATA                 223
#define ID_RENAME_SEGI                  224
#define ID_RETRIEVE_DATA                225
#define ID_COMPARE_DATA                 226
#define ID_EXPORT_RESULT                227
#define ID_EDIT_ITEM_PROP_ITEM          228
#define ID_RUN_DBP                      229
#define ID_FONTS_LIBRARY                230
#define ID_EXPORT_IMAGE_FILE            231
#define ID_232                          232
#define ID_IMMERSE_MODE                 233
#define ID_TYPEWRITER_MODE              234
#define ID_DELETE_PART                  235
#define ID_ADD_PART                     236
#define ID_COPY_ITEM                    237
#define ID_PASTE_ITEM                   238
#define ID_RETRIEVE_IMAGE_DATA          240
#define ID_TURN_ANTICLOCKWISE90         241
#define ID_TURN_CLOCKWISE90             242
#define ID_PICK_POINT_1                 244
#define ID_PICK_POINT_2                 245
#define ID_BUTTON246                    246
#define ID_BUTTON247                    247
#define ID_PICK_POINT_3                 248
#define ID_PICK_POINT_4                 249
#define ID_SELECT_FOLDER                256
#define ID_SETTING                      258
#define ID_MARK_ERROR                   261
#define ID_MARK_NORMAL                  262
#define ID_START_CALC                   265
#define ID_267                          267
#define ID_CONNECT_SCANNER              268
#define ID_269                          269
#define ID_OUTPUT_TBOM                  270
#define ID_LICENSE_CENTER               271
#define ID_RENAME_ITEM                  273
#define ID_MOVE_TO_TOP                  278
#define ID_MOVE_UP                      279
#define ID_MOVE_DOWN                    280
#define ID_MOVE_TO_BOTTOM               281
#define ID__282                         282
#define ID_EDIT_ITEM_PROP               283
#define ID_284                          284
#define ID_FILE_PROP                    285
#define ID_286                          286
#define ID_SET_CAD_PATH                 287
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_TOOLBAR1                    311
#define IDB_IL_PROJECT                  311
#define IDR_MENU1                       315
#define IDR_ITEM_CMD_POPUP              315
#define IDD_FILE_TREE_DLG               316
#define IDD_OUTPUT_INFO_DLG             318
#define IDD_DISP_DATA_PAGE              319
#define IDD_INPUT_PARTINFO_DLG          320
#define IDR_PICTURE_TOOL                321
#define IDD_INPUT_AN_STRING_VAL_DLG     321
#define IDD_RUN_DBP_DLG                 326
#define IDD_FONTS_LIBRARY_DLG           327
#define IDI_PIN_CROSS                   329
#define IDI_PIN_VERT                    330
#define IDC_CUR_ANCHOR                  330
#define IDC_CURSOR2                     331
#define IDC_CUR_PIN                     331
#define IDD_SETTING_DLG                 333
#define IDD_INPUT_PERFIX_AND_SUFFIX_DLG 334
#define IDB_BITMAP2                     338
#define IDB_BITMAP3                     340
#define IDB_SPLASH_IBOM                 340
#define IDD_AUTO_SAVE_PARAM_DLG         663
#define IDD_PAY_QRCODE_DLG              728
#define IDB_BMP_WXPAY_SYMBOL            729
#define IDB_BMP_WXPAY_FOOT              730
#define IDB_BMP_WXPAY_WELCOME           731
#define IDD_ENDUSER_APPLY_DLG           732
#define IDD_APPLY_CREDIT_RESULT_DLG     753
#define IDB_BMP_WXGH                    754
#define IDC_SETTING_LIST                1003
#define IDC_E_INPUT                     1004
#define IDC_MSG_MONEY                   1022
#define IDC_LIST_CTRL                   1035
#define IDC_PREV_LIST_CTRL2             1035
#define IDC_PREV_LIST_CTRL              1036
#define IDC_PREV_LIST_CTRL1             1036
#define IDC_FILE_LIST_CTRL              1037
#define IDC_E_RECORD_NUM                1058
#define IDC_E_CLIENTNAME                1058
#define IDC_E_PHONENUMBER               1059
#define IDC_E_WX_ACCOUNT                1060
#define IDC_E_VAL                       1093
#define IDC_PROGRESS_BAR                1185
#define IDC_NUMERIC_PROC                1186
#define IDC_S_TITLE                     1211
#define IDC_S_COPYRIGHT                 1217
#define IDC_WORK_PANEL                  1394
#define IDC_TREE_CTRL                   1545
#define IDC_E_PROP_HELP_STR             1546
#define IDC_AUTO_SAVE_TIME              1636
#define IDC_COM_SAVE_FILE_TYPE          1637
#define IDC_OUTPUT_INFO_LIST            1641
#define IDC_TAB_GROUP                   1642
#define IDC_S_RECORD_NUM                1647
#define IDC_SUB_WORK_PANEL              1648
#define IDC_E_PARTNO                    1649
#define IDC_S_SUM_WEIGHT_TITLE          1649
#define IDC_CMB_PART_TYPE               1650
#define IDC_S_RECORD_NUM3               1650
#define IDC_SUB_WORK_PANEL2             1650
#define IDC_CMB_GUIGE                   1651
#define IDC_S_PDF_ZOOM_SCALE_TITLE      1651
#define IDC_CMB_MATERIAL                1652
#define IDC_E_LENGHT                    1653
#define IDC_E_NUM                       1654
#define IDC_S_PARTNO                    1655
#define IDC_E_WEIGHT                    1656
#define IDC_E_SUM_WEIGHT                1657
#define IDC_PICTURE_PANEL               1658
#define IDC_LIST_NAME                   1659
#define IDC_S_MAT_GUIGE                 1660
#define IDC_S_LEN                       1661
#define IDC_S_NOTE                      1662
#define IDC_S_SUM_WEIGHT                1663
#define IDC_S_WEIGHT                    1664
#define IDC_S_NUM                       1665
#define IDC_CMB_CAD_PATH                1666
#define IDC_E_RECORD                    1667
#define IDC_E_TOLERANCE                 1668
#define IDC_E_COMPARE_TOLERANCE         1668
#define IDC_S_TOLERANCE_LABEL           1669
#define IDC_RICHEDIT21                  1670
#define IDC_S_TOLERANCE_LABEL2          1670
#define IDC_RICHEDIT22                  1671
#define IDC_CMB_FONTS                   1671
#define IDC_E_COMPARE_WEIGHT_TOLERANCE  1671
#define IDC_CMB_CHAR_IMAGE              1672
#define IDC_PIC_CHAR_IMAGE              1673
#define IDC_SPLITTER_HORIZ              1674
#define IDC_SLIDER_BALANCE_COEF         1675
#define IDC_S_BALANCE_COEF              1676
#define IDC_S_COEF_TITLE                1677
#define IDC_S_DISPLAY_MODEL             1678
#define IDC_CMB_MODEL                   1679
#define IDC_SLIDER_SPIN                 1681
#define IDC_S_PROMPT                    1682
#define IDC_TAB_CTRL                    1683
#define IDC_S_VERSION                   1684
#define IDC_E_PREFIX                    1685
#define IDC_E_SUFFIX                    1686
#define IDC_CMD_ROTATE_ANGLE            1687
#define IDC_SLIDER2                     1689
#define IDC_SLIDER_ZOOM_SCALE           1689
#define IDC_RENTAL_PERIOD               1771
#define IDC_RENTAL_ORDER_DATE           1772
#define IDC_ORDER_IDSTR                 1773
#define IDC_S_PIC_WXPAY_SYMBOL          1774
#define IDC_E_ENDUSER                   1775
#define IDD_PROC_BAR_DLG                6006
#define IDD_LICENSE_AHTORIZE_DLG1       15000
#define IDD_LICENSE_AHTORIZE_DLG        15000
#define IDD_LICENSE_SERVER_ACTIVATE_DLG 15001
#define IDD_LICENSE_VIRTUAL_RENTAL_DLG  15002
#define IDC_RDO_DOG_TYPE4               15004
#define IDC_BN_SHIFT_TO_SERVER_LICENSE  15007
#define IDC_BN_CREATE_IDENTITY_FILE     15008
#define IDC_BN_APPLY_LICENSE_ONLINE     15011
#define IDC_S_PORT_NUMBER               15020
#define IDC_E_PORT_NUMBER               15023
#define IDC_CMB_RENTAL_PERIOD           15024
#define IDC_BN_SHIFT_TO_END_LICENSE     15025
#define IDC_S_RAND_APPLY_CODE           15026
#define IDC_S_MSG_NO_CLOSE              15027
#define IDC_BN_SHIFT_TO_VIRTUAL_LICENSE 15028
#define IDD_LICENSE_ONLINE_RENTAL_DLG   15029
#define IDC_MSG                         15030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        341
#define _APS_NEXT_COMMAND_VALUE         288
#define _APS_NEXT_CONTROL_VALUE         1690
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
